NBcrm/NBcrm/urls.py
from django.conf.urls import url
from django.contrib import admin

from nbapp import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #首页
    url(r'^index/', views.index,name='index'),

    #注册
    url(r'^register/', views.register, name='register'),

    #登录
    url(r'^login/', views.login, name='login'),

    #验证码
    url(r'^get_valid_img/', views.get_valid_img, name='get_valid_img'),

    #注销
    url(r'^logout/', views.logout, name='logout'),
    # url(r'^shopping/', views.shopping, name='shopping'),
    #展示所有公户客户信息
    url(r'^customers/list/', views.customers, name='customers'),

    # 私户信息展示
    url(r'^mycustomers/', views.customers, name='mycustomers'),


    #添加
    url(r'^add/', views.add, name='add'),

    #编辑
    url(r'^edit/(\d+)/', views.edit, name='edit'),

    #删除
    url(r'^delete/(\d+)/', views.delete, name='delete'),

    #搜索
    url(r'^se/', views.se, name='se'),

    url(r'^se_follow/', views.se_follow, name='se_follow'),


    #批量操作

    url(r'^batch/', views.batch, name='batch'),

    # 跟进批量操作

    url(r'^batch_follow/', views.batch_follow, name='batch_follow'),

    #跟进记录

    url(r'^follow/', views.follow, name='follow'),
    #添加跟进记录

    url(r'^add_follow/', views.add_follow, name='add_follow'),
    #编辑跟进记录

    url(r'^edit_follow/(\d+)/', views.edit_follow, name='edit_follow'),
    #删除跟进记录

    url(r'^delete_follow/(\d+)/', views.delete_follow, name='delete_follow'),


    #班级学习记录
    url(r'^class_record/',views.ClassRecordView.as_view(),name='class_record'),

    # 学生详细记录
    url(r'^study_decord/(\d+)/',views.StudyRecordDetialView.as_view(),name='study_decord'),

    #添加班级记录
    url(r'^add_record/',views.ClassRecordView_add.as_view(),name='add_record'),
    #编辑班级记录
    url(r'^edit_record/(\d+)/',views.ClassRecordView_edit.as_view(),name='edit_record'),

    #删除班级记录
    url(r'^del_record/(\d+)/',views.ClassRecordView_del.as_view(),name='del_record'),

    #权限分配
    url(r'^menu_list/',views.menu_list,name='menu_list'),


]

NBcrm/nbapp/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser


from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
#安装:pip install django-multiselectfield,针对choices多选用的

from django.utils.safestring import mark_safe

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)





class UserInfo(AbstractUser):

    roles=models.ManyToManyField('Role')

    #销售,班主任,讲师,三哥

    telephone = models.CharField(max_length=32,null=True)
    dep=models.ForeignKey('Department',null=True,on_delete=True)
    def __str__(self):
        return self.username
#新添加个部门表
class Department(models.Model):
    '''
    部门表
    '''
    name = models.CharField(max_length=12,verbose_name='部门名称')
    count = models.IntegerField(verbose_name='部门人数')

class Menu(models.Model):
    title=models.CharField(verbose_name="一级菜单",max_length=32,null=True,blank=True)
    icon=models.CharField(verbose_name='图标',max_length=32,null=True,blank=True)




class Role(models.Model):
    title=models.CharField(max_length=32)
    permissions=models.ManyToManyField('Permission')

    def __str__(self):
        return self.title

class Permission(models.Model):
    title=models.CharField(max_length=32)
    url=models.CharField(max_length=128)
    menu=models.ForeignKey('Menu',null=True,blank=True,on_delete=True)
    pid=models.ForeignKey('self',null=True,blank=True,on_delete=True)
    # is_menus=models.BooleanField(default=False)
    # icon=models.CharField(max_length=32,null=True,blank=True)
    def __str__(self):
        return self.title





class Customer(models.Model):
    """
    客户表（最开始的时候大家都是客户，销售就不停的撩你，你还没交钱就是个客户）
    """
    qq = models.CharField(verbose_name='QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True) #存的是male或者female，字符串
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)

    phone = models.CharField('手机号', blank=True, null=True,max_length=32)
    # phone = models.CharField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')

    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True,on_delete=True)  #self指的就是自己这个表，和下面写法是一样的效果


    # introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices,null=True) #多选，并且存成一个列表的格式
    # course = models.CharField("咨询课程", choices=course_choices) #如果你不想用上面的多选功能，可以使用Charfield来存
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",help_text="选择客户此时的状态") #help_text这种参数基本都是针对admin应用里面用的

    date = models.DateTimeField("咨询日期", auto_now_add=True)

    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True) #考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True) #销售自己大概记录一下自己下一次会什么时候跟进，也没啥用

    #用户表中存放的是自己公司的所有员工。
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", blank=True, null=True,on_delete=True)


    #一个客户可以报多个班，报个脱产班，再报个周末班等，所以是多对多。
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级",) #去掉了null


    def __str__(self):
        return self.name+":"+self.qq  #主要__str__最好是个字符串昂，不然你会遇到很多的坑，还有我们返回的这两个字段填写数据的时候必须写上数据，必然相加会报错，null类型和str类型不能相加等错误信息。


    def get_classlist(self):  #当我们通过self.get_classlist的时候，就拿到了所有的班级信息，前端显示的时候用

        l=[]
        for cls in self.class_list.all():
            l.append(str(cls))
        # return mark_safe(",".join(l)) #纯文本，不用mark_safe也可以昂
        return ",".join(l) #纯文本，不用mark_safe也可以昂


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name




class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期") #python20期等
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True) #不一定什么时候结业，哈哈，所以可为空

    #contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo', verbose_name="老师") #对了，还有一点，如果你用的django2版本的，那么外键字段都需要自行写上on_delete=models.CASCADE

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)




class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户",on_delete=True)

    note = models.TextField(verbose_name="跟进内容...")

    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")

    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records',on_delete=True)

    date = models.DateTimeField("跟进日期", auto_now_add=True)

    # delete_status = models.BooleanField(verbose_name='删除状态', default=False)


#权限表


############################学员系统相关的表，暂时不用先关掉####################
class Student(models.Model):
    """
    学生表（已报名）
    """
    customer = models.OneToOneField(verbose_name='客户信息', to='Customer',on_delete=models.CASCADE,null=True,blank=True)
    class_list = models.ManyToManyField(verbose_name="已报班级", to='ClassList', blank=True,related_name="students")

    emergency_contract = models.CharField(max_length=32, blank=True, null=True, verbose_name='紧急联系人')
    company = models.CharField(verbose_name='公司', max_length=128, blank=True, null=True)
    location = models.CharField(max_length=64, verbose_name='所在区域', blank=True, null=True)
    position = models.CharField(verbose_name='岗位', max_length=64, blank=True, null=True)
    salary = models.IntegerField(verbose_name='薪资', blank=True, null=True)
    welfare = models.CharField(verbose_name='福利', max_length=256, blank=True, null=True)
    date = models.DateField(verbose_name='入职时间', help_text='格式yyyy-mm-dd', blank=True, null=True)
    memo = models.CharField(verbose_name='备注', max_length=256, blank=True, null=True)

    def __str__(self):
        return self.customer.name

class ClassStudyRecord(models.Model):
    """
    上课记录表 （班级记录）
    """
    class_obj = models.ForeignKey(verbose_name="班级", to="ClassList",on_delete=models.CASCADE)
    day_num = models.IntegerField(verbose_name="节次", help_text=u"此处填写第几节课或第几天课程...,必须为数字")

    teacher = models.ForeignKey(verbose_name="讲师", to='UserInfo',on_delete=models.CASCADE)
    date = models.DateField(verbose_name="上课日期", auto_now_add=True)
    course_title = models.CharField(verbose_name='本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField(verbose_name='本节课程内容概要', blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业",blank=True)
    homework_title = models.CharField(verbose_name='本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField(verbose_name='作业描述', max_length=500, blank=True, null=True)

NBcrm/templates/add.html
{% extends 'base.html' %}


{% block content %}
    <form action="{% url 'add' %}" method="post">
    {% csrf_token %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-xs-8">
            {% for form in form_obj %}
                <label for="{{ form.id_for_label }}">{{ form.label }}</label>
                {{ form }}
                <span class="text-danger">{{ form.errors.0 }}</span>
            {% endfor %}


        </div>
    </div>

<button  type="submit" class="btn btn-primary">添加</button>

</div>
{% endblock %}

</form>

NBcrm/templates/add_follow.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {% for field in form_obj %}

        <label for="{{ field.id_for_label }}">{{ field.label }}</label>

        

        {{ field }}
        <span class="text-danger">{{ field.errors.0 }}</span>


    {% endfor %}

    <button type="submit" class="btn btn-primary">添加</button>
</form>
</div>
{% endblock %}

NBcrm/templates/customers.html
{% extends 'base.html' %}
{% load mytags %}
{% block content %}

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">

                        <br>
                        {% if "/add/"|haspermission:request %}
                            {% if not  flag %}
                                <a href="{% url 'add' %}" class="btn btn-primary pull-right" style="margin-left: 50px">添加</a>

                            {% endif %}




                        {% endif %}
                        <form action="{% url 'se' %}" method="get" class="pull-right">
                            <input type="text" name="wd" class="form-control pull-right" style="width: 150px">
                            <select name="condition" id="" class="form-control pull-right" style="width: 80px">
                                <option value="name__contains">姓名</option>
                                <option value="qq__contains">QQ</option>
                            </select>
                             <button class="pull-right btn btn-default">搜索</button>
                        </form>
{#                        批量操作#}
                        <form action="" method="post" class="">
                            {% csrf_token %}

                            <select name="action" id="" class="form-control pull-left" style="width: 150px">
                            {% if "/btatch_delete/"|haspermission:reuqest %}
                                <option value="batch_delete">批量删除</option>
                            {% endif %}
                                {% if "/batch_update/"|haspermission:reuqest %}
                                <option value="batch_update">批量更新客户状态</option>
                                {% endif %}

                                {% if "/reverse_sg/"|haspermission:reuqest or "/reverse_gs/"|haspermission:reuqest %}
                                                       {% if flag %}
                                <option value="reverse_sg">私户转公户</option>
                                    {% else %}
                                    <option value="reverse_gs">公户转私户</option>
                                {% endif %}
                                {% endif %}



{#                                <option value="reverse_sg">私户转公户</option>#}

                            </select>
                            {% if name_li %}
                                {% for name in name_li %}
                                    {{ name }}信息已被他人占用
                                {% endfor %}
                            {% endif %}
                            <button type="submit" class="btn pull-left btn-warning">提交</button>

                            <br>
                    <!-- /.box-header -->
                    <div class="box-body">
{#                    <h3>{{ flag }}</h3>#}
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th><input type="checkbox" id="choose"></th>
                                <th>序号</th>
                                <th>qq</th>
                                <th>姓名</th>
                                <th>性别</th>
                                <th>客户来源</th>
{#                                <th>转介绍自学员</th>#}
                                <th>咨询课程</th>
                                <th>选择客户此时的状态</th>
                                <th>销售</th>
                                {% if "/edit/"|haspermission:request or "/delete/"|haspermission:request %}
                                <th>操作</th>
                                {% endif %}

                            </tr>
                            </thead>
                            <tbody>
                                {% for customer in all_customers %}
                                    <tr>
                                        <td><input type="checkbox" name="selected_id" value="{{ customer.pk }}"></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ customer.qq }}</td>
                                        <td>{{ customer.name }}</td>
                                        <td>{{ customer.get_sex_display }}</td>
                                        <td>{{ customer.get_source_display }}</td>
{#                                        <td>{{ customer.introduce_from.name }}</td>#}
                                        <td>{{ customer.course }}</td>
                                        <td>{{ customer.get_status_display|default:'未报名' }}</td>
                                        <td>{{ customer.consultant.username|default:'暂无' }}</td>
{#                                        <td>{{ customer.get_classlist }}</td>#}
                                        <td>
                                            {% if "/edit/"|haspermission:request %}
                                                <a href="{% url 'edit' customer.pk %}" class="btn btn-warning">编辑</a>

                                            {% endif %}
                                        {% if "/delete/"|haspermission:request %}
                                            <a href="{% url 'delete' customer.pk %}" class="btn btn-danger">删除</a>

                                        {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                     </div>
                    <!-- /.box-body -->
                    </form>
                </div>
                <!-- /.box -->
                 </div>
            <!-- /.col -->
             </div>
         </div>
        <!-- /.row -->
    </section>

{{ ret_html|safe }}


{% endblock %}

{% block js %}
    <script>
    $('#choose').click(function () {
        var status=$(this).prop('checked')
        $('[name=selected_id]').prop('checked',status);

    })


    </script>
{% endblock %}

NBcrm/templates/edit.html
{% extends 'base.html' %}

{% block content %}

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>


                    {% endfor %}

                <button class="btn btn-primary pull-right">提交</button>

                </form>
            </div>
        </div>

    </div>


{% endblock %}

NBcrm/templates/follow.html
{% extends 'base.html' %}

{% block content %}

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <div><h1 class="box-title">个人客户跟进记录</h1></div>
                         <a href="{% url 'add_follow' %}" class="btn btn-primary pull-right" style="margin-left: 50px">添加</a>
                        <form action="{% url 'se_follow' %}" method="get" class="pull-right">
                            <input type="text" name="wd" class="form-control pull-right" style="width: 150px">
                            <select name="condition" id="" class="form-control pull-right" style="width: 80px">
                                <option value="customer__name__contains">客户</option>
{#                                <option value="qq__contains">QQ</option>#}
                            </select>
                             <button class="pull-right btn btn-default">搜索</button>
                        </form>
{#                        批量操作#}
                        <form action="{% url 'batch_follow' %}" method="post" class="">
                            {% csrf_token %}
                            <select name="action" id="" class="form-control pull-left" style="width: 150px">
                                <option value="batch_delete_follow">批量删除</option>
                                <option value="batch_update_follow">批量更新客户状态</option>
{#                                <option value="reverse_gs">公户转私户</option>#}
{#                                <option value="reverse_sg">私户转公户</option>#}

                            </select>
                            <button type="submit" class="btn pull-left btn-warning">提交</button>

                    <!-- /.box-header -->
                    <div class="box-body">
{#                    <h3>{{ flag }}</h3>#}
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th><input type="checkbox" id="choose"></th>
                                <th>序号</th>
                                <th>所咨询客户</th>
                                <th>跟进内容</th>
                                <th>跟进状态</th>
                                <th>跟进人</th>
{#                                <th>转介绍自学员</th>#}
                                <th>跟进日期</th>
{#                                <th>选择客户此时的状态</th>#}
{#                                <th>销售</th>#}
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for customer in form_obj %}
                                    <tr>
                                        <td><input type="checkbox" name="selected_id" value="{{ customer.pk }}"></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ customer.customer }}</td>
                                        <td>{{ customer.note }}</td>
                                        <td>{{ customer.get_status_display }}</td>
                                        <td>{{ customer.consultant.username }}</td>
{#                                        <td>{{ customer.introduce_from.name }}</td>#}
                                        <td>{{ customer.date|date:'Y-m-d' }}</td>
{#                                        <td>{{ customer.get_status_display|default:'未报名' }}</td>#}
{#                                        <td>{{ customer.consultant.username|default:'暂无' }}</td>#}
{#                                        <td>{{ customer.get_classlist }}</td>#}
                                        <td>
                                            <a href="{% url 'edit_follow' customer.pk %}" class="btn btn-warning">编辑</a>
                                            <a href="{% url 'delete_follow' customer.pk %}" class="btn btn-danger">删除</a>
                                        </td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                     </div>
                    <!-- /.box-body -->
                    </form>
                </div>
                <!-- /.box -->
                 </div>
            <!-- /.col -->
             </div>
         </div>
        <!-- /.row -->
    </section>

{{ ret_html|safe }}


{% endblock %}

{% block js %}
    <script>
    $('#choose').click(function () {
        var status=$(this).prop('checked')
        $('[name=selected_id]').prop('checked',status);

    })
    </script>
{% endblock %}

NBcrm/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block js %}
    <script src="{% static 'js/index_js.js' %}">



    </script>

{% endblock %}

NBcrm/templates/left_menu.html
<div class="multi-menu">
            {#主页#}
            <div class="title_1">
                <a class="btn btn-primary" style="width: 230px" href="{% url 'index' %}" > <i class=""></i> 主页</a>
            </div>


    {% for item in menu_dict.values %}

        <div class="item">
            <div class="title">
                <i class="{{ item.icon }} btn btn-primary" style="width: 230px;height: 30px">{{ item.title }}</i>
            </div>
            {% for child in item.children %}
                <div class="body {{ item.class }} ">
                    <a href="{{ child.url }}" class="{{ child.class }} btn btn-default " style="width: 230px;">{{ child.title }}</a>
                </div>
            {% endfor %}

        </div>

    {% endfor %}

</div>

NBcrm/templates/mycustomers.html
{% extends 'base.html' %}

{% block content %}

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <div><h1 class="box-title">个人客户信息展示</h1></div>
{#                         <a href="{% url 'add' %}" class="btn btn-primary pull-right" style="margin-left: 50px">添加</a>#}
                        <form action="{% url 'se' %}" method="get" class="pull-right">
                            <input type="text" name="wd" class="form-control pull-right" style="width: 150px">
                            <select name="condition" id="" class="form-control pull-right" style="width: 80px">
                                <option value="name__contains">姓名</option>
                                <option value="qq__contains">QQ</option>
                            </select>
                             <button class="pull-right btn btn-default">搜索</button>
                        </form>
{#                        批量操作#}
                        <form action="{% url 'batch' %}" method="post" class="">
                            {% csrf_token %}
                            <select name="action" id="" class="form-control pull-left" style="width: 150px">
                                <option value="batch_delete">批量删除</option>
                                <option value="batch_update">批量更新客户状态</option>
{#                                <option value="reverse_gs">公户转私户</option>#}
                                <option value="reverse_sg">私户转公户</option>

                            </select>
                            <button type="submit" class="btn pull-left btn-warning">提交</button>

                    <!-- /.box-header -->
                    <div class="box-body">
                    <h3>{{ flag }}</h3>
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th><input type="checkbox" id="choose"></th>
                                <th>序号</th>
                                <th>qq</th>
                                <th>姓名</th>
                                <th>性别</th>
                                <th>客户来源</th>
{#                                <th>转介绍自学员</th>#}
                                <th>咨询课程</th>
                                <th>选择客户此时的状态</th>
                                <th>销售</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for customer in all_customers %}
                                    <tr>
                                        <td><input type="checkbox" name="selected_id" value="{{ customer.pk }}"></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ customer.qq }}</td>
                                        <td>{{ customer.name }}</td>
                                        <td>{{ customer.get_sex_display }}</td>
                                        <td>{{ customer.get_source_display }}</td>
{#                                        <td>{{ customer.introduce_from.name }}</td>#}
                                        <td>{{ customer.course }}</td>
                                        <td>{{ customer.get_status_display|default:'未报名' }}</td>
                                        <td>{{ customer.consultant.username|default:'暂无' }}</td>
{#                                        <td>{{ customer.get_classlist }}</td>#}
                                        <td>
                                            <a href="{% url 'edit' customer.pk %}" class="btn btn-warning">编辑</a>
                                            <a href="{% url 'delete' customer.pk %}" class="btn btn-danger">删除</a>
                                        </td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                     </div>
                    <!-- /.box-body -->
                    </form>
                </div>
                <!-- /.box -->
                 </div>
            <!-- /.col -->
             </div>
         </div>
        <!-- /.row -->
    </section>

{{ ret_html|safe }}


{% endblock %}

{% block js %}
    <script>
    $('#choose').click(function () {
        var status=$(this).prop('checked')
        $('[name=selected_id]').prop('checked',status);

    })
    </script>
{% endblock %}

NBcrm/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>

<h1>这是注册页面</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="{% url 'register' %}" method="post" novalidate>
                {% csrf_token %}
                {% for field in form_obj %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="text-danger">{{ field.errors.0 }}</span>
                    </div>

                {% endfor %}

                <input type="submit" class="btn btn-success pull-right" value="注册">

            </form>

        </div>
    </div>

</div>


<script src="{% static 'jquery-3.4.1.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
<script>


</script>
</body>
</html>